function [coords] = pixToPos(pix_lims, pos_lims, x)
    % Lims should be a 2x2 array of [x0, x1; y0, y1]
    % x should be a nx2 array of x,y positions
    coords = [(x(:,1)-pix_lims(1,1))/(pix_lims(1,2) - pix_lims(1,1)) ...
        * (pos_lims(1,2) - pos_lims(1,1)) + pos_lims(1,1), ...
        (x(:,2)-pix_lims(2,1))/(pix_lims(2,2) - pix_lims(2,1)) ...
        * (pos_lims(2,2) - pos_lims(2,1)) + pos_lims(2,1)];
end