function plotDoors(locs, closed)
    doors = {'AB', 'BA', 'BC', 'CB', 'CD', 'DC', 'DA', 'AD'};    
    isClosed = ismember(1:8, closed);
    markers = cell(size(doors));
    for currDoor = 1:length(isClosed)
        if isClosed(currDoor)
            markers{currDoor} = '-';
        else
            markers{currDoor} = ':';
        end
    end
    doorWidth = 40;
    doorSep = 5;
    lineWidth = 2;
    %  Plot line for each door
    plot([locs(1,1) - 0.5*doorSep; locs(1,1) - 0.5*doorSep],...
        [locs(1,2) - 0.5*doorWidth; locs(1,2) + 0.5*doorWidth], ...
        ['k' markers{1}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % AB
    plot([locs(1,1) + 0.5*doorSep; locs(1,1) + 0.5*doorSep],...
        [locs(1,2) - 0.5*doorWidth; locs(1,2) + 0.5*doorWidth], ...
        ['k' markers{2}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % BA
    plot([locs(2,1) - 0.5*doorWidth, locs(2,1) + 0.5*doorWidth],...
        [locs(2,2) + 0.5*doorSep, locs(2,2) + 0.5*doorSep], ...
        ['k' markers{3}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % BC
    plot([locs(2,1) - 0.5*doorWidth, locs(2,1) + 0.5*doorWidth],...
        [locs(2,2) - 0.5*doorSep, locs(2,2) - 0.5*doorSep], ...
        ['k' markers{4}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % CB
    plot([locs(3,1) + 0.5*doorSep; locs(3,1) + 0.5*doorSep],...
        [locs(3,2) - 0.5*doorWidth; locs(3,2) + 0.5*doorWidth], ...
        ['k' markers{5}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % CD    
    plot([locs(3,1) - 0.5*doorSep; locs(3,1) - 0.5*doorSep],...
        [locs(3,2) - 0.5*doorWidth; locs(3,2) + 0.5*doorWidth], ...
        ['k' markers{6}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % DC
    plot([locs(4,1) - 0.5*doorWidth, locs(4,1) + 0.5*doorWidth],...
        [locs(4,2) - 0.5*doorSep, locs(4,2) - 0.5*doorSep], ...
        ['k' markers{7}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % DA    
    plot([locs(4,1) - 0.5*doorWidth, locs(4,1) + 0.5*doorWidth],...
        [locs(4,2) + 0.5*doorSep, locs(4,2) + 0.5*doorSep], ...
        ['k' markers{8}], 'LineWidth', lineWidth, 'HandleVisibility','off'); % AD
end